from .base_strategy import TorchTensorBaseClassificationStrategy
from .binary_strategy import TorchTensorBinaryClassificationStrategy
from .multi_label_strategy import TorchTensorMultiLabelClassificationStrategy
from .multiclass_strategy import TorchTensorMulticlassClassificationStrategy
