"""
Default service types used in ``City`` model
"""

SERVICE_TYPES = [
    {
        "code": "3.5.1",
        "name": "school",
        "demand": 120,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 250, "area": 1.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 300, "area": 1.1, "is_integrated": False, "parking_area": 0},
            {"capacity": 600, "area": 1.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 1100, "area": 1.8, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 0.2, "is_integrated": True, "parking_area": 0.02},
            {"capacity": 300, "area": 0.36, "is_integrated": True, "parking_area": 0.03},
            {"capacity": 600, "area": 0.8, "is_integrated": True, "parking_area": 0.06},
            {"capacity": 1100, "area": 1.1, "is_integrated": True, "parking_area": 0.1},
        ],
    },
    {
        "code": "3.5.1",
        "name": "kindergarten",
        "demand": 61,
        "accessibility": 7,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 180, "area": 0.72, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 1.44, "is_integrated": False, "parking_area": 0},
            {"capacity": 280, "area": 1.1, "is_integrated": False, "parking_area": 0},
            {"capacity": 180, "area": 0.54, "is_integrated": True, "parking_area": 0.025},
            {"capacity": 250, "area": 0.76, "is_integrated": True, "parking_area": 0.03},
            {"capacity": 280, "area": 0.84, "is_integrated": True, "parking_area": 0.032},
        ],
    },
    {
        "code": "3.4.2",
        "name": "hospital",
        "demand": 9,
        "accessibility": 60,
        "land_use": ["mixed_use", "business", "special"],
        "bricks": [
            {"capacity": 110, "area": 0.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 400, "area": 2.5, "is_integrated": False, "parking_area": 0},
            {"capacity": 925, "area": 6.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 1200, "area": 5.8, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "3.4.1",
        "name": "polyclinic",
        "demand": 13,
        "accessibility": 10,
        "land_use": ["residential", "mixed_use", "business", "special", "industrial"],
        "bricks": [
            {"capacity": 100, "area": 0.15, "is_integrated": False, "parking_area": 0},
            {"capacity": 150, "area": 0.21, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 0.34, "is_integrated": False, "parking_area": 0},
            {"capacity": 500, "area": 0.65, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.12, "is_integrated": True, "parking_area": 0.0125},
            {"capacity": 150, "area": 0.17, "is_integrated": True, "parking_area": 0.015},
            {"capacity": 250, "area": 0.26, "is_integrated": True, "parking_area": 0.02},
            {"capacity": 500, "area": 0.5, "is_integrated": True, "parking_area": 0.025},
        ],
    },
    {
        "code": "5.1.3",
        "name": "pitch",
        "demand": 10,
        "accessibility": 60,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 10, "area": 0.015, "is_integrated": False, "parking_area": 0},
            {"capacity": 32, "area": 0.6, "is_integrated": False, "parking_area": 0},
            {"capacity": 48, "area": 0.8, "is_integrated": False, "parking_area": 0},
            {"capacity": 10, "area": 0.008, "is_integrated": True, "parking_area": 0.005},
            {"capacity": 32, "area": 0.5, "is_integrated": True, "parking_area": 0.015},
            {"capacity": 48, "area": 0.7, "is_integrated": True, "parking_area": 0.025},
        ],
    },
    {
        "code": "5.1.2",
        "name": "swimming_pool",
        "demand": 8,
        "accessibility": 30,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 50, "area": 0.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 1.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 300, "area": 3.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 30, "area": 0.2, "is_integrated": True, "parking_area": 0.0125},
            {"capacity": 50, "area": 0.3, "is_integrated": True, "parking_area": 0.022},
            {"capacity": 100, "area": 0.7, "is_integrated": True, "parking_area": 0.05},
        ],
    },
    {
        "code": "5.1.1",
        "name": "stadium",
        "demand": 10,
        "accessibility": 30,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 2000, "area": 12.75, "is_integrated": False, "parking_area": 0},
            {"capacity": 21000, "area": 28.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 62300, "area": 70.1, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "3.6.1",
        "name": "theatre",
        "demand": 6,
        "accessibility": 60,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 800, "area": 0.5, "is_integrated": False, "parking_area": 0},
            {"capacity": 1200, "area": 0.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 1600, "area": 1.1, "is_integrated": False, "parking_area": 0},
            {"capacity": 890, "area": 0.4, "is_integrated": True, "parking_area": 0.325},
            {"capacity": 1600, "area": 0.7, "is_integrated": True, "parking_area": 0.6},
            {"capacity": 1400, "area": 1.1, "is_integrated": True, "parking_area": 0.5},
        ],
    },
    {
        "code": "3.6.1",
        "name": "museum",
        "demand": 3,
        "accessibility": 60,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 1000, "area": 1.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 3500, "area": 13.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 10000, "area": 23.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 200, "area": 0.05, "is_integrated": True, "parking_area": 0.325},
            {"capacity": 700, "area": 0.25, "is_integrated": True, "parking_area": 0.187},
            {"capacity": 1000, "area": 0.8, "is_integrated": True, "parking_area": 0.275},
        ],
    },
    {
        "code": "3.6.1",
        "name": "cinema",
        "demand": 9,
        "accessibility": 60,
        "land_use": ["residential", "mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 680, "area": 0.25, "is_integrated": False, "parking_area": 0},
            {"capacity": 560, "area": 0.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 500, "area": 0.15, "is_integrated": True, "parking_area": 0.13},
            {"capacity": 760, "area": 0.25, "is_integrated": True, "parking_area": 0.2},
            {"capacity": 1000, "area": 0.32, "is_integrated": True, "parking_area": 0.28},
        ],
    },
    {
        "code": "4.2",
        "name": "mall",
        "demand": 8,
        "accessibility": 30,
        "land_use": ["mixed_use", "business"],
        "bricks": [
            {"capacity": 7000, "area": 1.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 10000, "area": 2.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 18000, "area": 3.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 1000, "area": 0.08, "is_integrated": True, "parking_area": 0.05},
            {"capacity": 4000, "area": 0.4, "is_integrated": True, "parking_area": 0.25},
            {"capacity": 10000, "area": 1.3, "is_integrated": True, "parking_area": 0.81},
        ],
    },
    {
        "code": "4.4",
        "name": "convenience",
        "demand": 180,
        "accessibility": 5,
        "land_use": ["residential", "mixed_use", "business", "industrial"],
        "bricks": [
            {"capacity": 50, "area": 0.003, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.0065, "is_integrated": False, "parking_area": 0},
            {"capacity": 160, "area": 0.008, "is_integrated": False, "parking_area": 0},
            {"capacity": 50, "area": 0.0025, "is_integrated": True, "parking_area": 0.005},
            {"capacity": 100, "area": 0.005, "is_integrated": True, "parking_area": 0.005},
            {"capacity": 180, "area": 0.0075, "is_integrated": True, "parking_area": 0.005},
        ],
    },
    {
        "code": "4.4",
        "name": "supermarket",
        "demand": 900,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business", "industrial"],
        "bricks": [
            {"capacity": 200, "area": 0.015, "is_integrated": False, "parking_area": 0},
            {"capacity": 1500, "area": 0.03, "is_integrated": False, "parking_area": 0},
            {"capacity": 1000, "area": 0.07, "is_integrated": False, "parking_area": 0},
            {"capacity": 3500, "area": 0.25, "is_integrated": False, "parking_area": 0},
            {"capacity": 200, "area": 0.015, "is_integrated": True, "parking_area": 0.0075},
            {"capacity": 500, "area": 0.03, "is_integrated": True, "parking_area": 0.0125},
            {"capacity": 1000, "area": 0.07, "is_integrated": True, "parking_area": 0.025},
        ],
    },
    {
        "code": "12.1",
        "name": "cemetery",
        "demand": 96,
        "accessibility": 40,
        "land_use": ["special"],
        "bricks": [
            {"capacity": 3200, "area": 8.6, "is_integrated": False, "parking_area": 0},
            {"capacity": 10800, "area": 27, "is_integrated": False, "parking_area": 0},
            {"capacity": 21000, "area": 51, "is_integrated": False, "parking_area": 0},
            {"capacity": 280000, "area": 70, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "3.7.1",
        "name": "religion",
        "demand": 10,
        "accessibility": 30,
        "land_use": ["mixed_use", "business", "special"],
        "bricks": [
            {"capacity": 1300, "area": 1.8, "is_integrated": False, "parking_area": 0},
            {"capacity": 2700, "area": 4.65, "is_integrated": False, "parking_area": 0},
            {"capacity": 3000, "area": 5.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 6000, "area": 10, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "4.3",
        "name": "marketplace",
        "demand": 800,
        "accessibility": 30,
        "land_use": ["mixed_use", "business", "industrial", "agriculture"],
        "bricks": [
            {"capacity": 15000, "area": 1.1, "is_integrated": False, "parking_area": 0},
            {"capacity": 21000, "area": 3, "is_integrated": False, "parking_area": 0},
            {"capacity": 35000, "area": 5, "is_integrated": False, "parking_area": 0},
            {"capacity": 50000, "area": 14, "is_integrated": False, "parking_area": 0},
            {"capacity": 2500, "area": 0.027, "is_integrated": True, "parking_area": 0.017},
            {"capacity": 9100, "area": 1, "is_integrated": True, "parking_area": 0.0625},
            {"capacity": 29200, "area": 3.2, "is_integrated": True, "parking_area": 0.2},
        ],
    },
    {
        "code": "4.8.1",
        "name": "bowling_alley",
        "demand": 9,
        "accessibility": 60,
        "land_use": ["mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 80, "area": 0.07, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 0.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 900, "area": 0.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.07, "is_integrated": True, "parking_area": 0.025},
            {"capacity": 300, "area": 0.2, "is_integrated": True, "parking_area": 0.075},
            {"capacity": 1000, "area": 0.7, "is_integrated": True, "parking_area": 0.25},
        ],
    },
    {
        "code": "7.12",
        "name": "train_building",
        "demand": 33,
        "accessibility": 60,
        "land_use": [],
        "bricks": [
            {"capacity": 25000, "area": 1.06, "is_integrated": False, "parking_area": 0},
            {"capacity": 16000, "area": 1.72, "is_integrated": False, "parking_area": 0},
            {"capacity": 37000, "area": 2, "is_integrated": False, "parking_area": 0},
            {"capacity": 68000, "area": 2.2, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "4.5",
        "name": "bank",
        "demand": 20,
        "accessibility": 30,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 250, "area": 0.045, "is_integrated": False, "parking_area": 0},
            {"capacity": 500, "area": 0.08, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 0.04, "is_integrated": True, "parking_area": 0.0325},
            {"capacity": 500, "area": 0.075, "is_integrated": True, "parking_area": 0.058},
        ],
    },
    {
        "code": "4.1",
        "name": "lawyer",
        "demand": 14,
        "accessibility": 30,
        "land_use": ["mixed_use", "business", "industrial"],
        "bricks": [
            {"capacity": 250, "area": 0.045, "is_integrated": False, "parking_area": 0},
            {"capacity": 500, "area": 0.08, "is_integrated": False, "parking_area": 0},
            {"capacity": 250, "area": 0.04, "is_integrated": True, "parking_area": 0.0125},
            {"capacity": 500, "area": 0.07, "is_integrated": True, "parking_area": 0.025},
        ],
    },
    {
        "code": "4.6",
        "name": "cafe",
        "demand": 25,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 25, "area": 0.15, "is_integrated": False, "parking_area": 0.02},
            {"capacity": 45, "area": 0.075, "is_integrated": False, "parking_area": 0.0375},
            {"capacity": 90, "area": 0.038, "is_integrated": False, "parking_area": 0.11},
            {"capacity": 65, "area": 0.028, "is_integrated": False, "parking_area": 0.0875},
            {"capacity": 30, "area": 0.15, "is_integrated": True, "parking_area": 0.02},
            {"capacity": 50, "area": 0.075, "is_integrated": True, "parking_area": 0.0375},
            {"capacity": 100, "area": 0.038, "is_integrated": True, "parking_area": 0.11},
            {"capacity": 70, "area": 0.028, "is_integrated": True, "parking_area": 0.0875},
        ],
    },
    {
        "code": "7.6",
        "name": "subway_entrance",
        "demand": 408,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business", "recreation", "industrial", "agriculture", "transport"],
        "bricks": [
            {"capacity": 30000, "area": 1.4, "is_integrated": False, "parking_area": 0},
            {"capacity": 50000, "area": 1.5, "is_integrated": False, "parking_area": 0},
            {"capacity": 65000, "area": 1.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 30000, "area": 1.4, "is_integrated": True, "parking_area": 0.05},
            {"capacity": 50000, "area": 1.5, "is_integrated": True, "parking_area": 0.25},
            {"capacity": 65000, "area": 1.7, "is_integrated": True, "parking_area": 0.81},
        ],
    },
    {
        "code": "3.22",
        "name": "multifunctional_center",
        "demand": 408,
        "accessibility": 15,
        "land_use": [],
        "bricks": [
            {"capacity": 80, "area": 0.07, "is_integrated": True, "parking_area": 0.04},
            {"capacity": 100, "area": 0.1, "is_integrated": True, "parking_area": 0.06},
            {"capacity": 200, "area": 0.12, "is_integrated": True, "parking_area": 0.07},
        ],
    },
    {
        "code": "3.3",
        "name": "hairdresser",
        "demand": 10,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 20, "area": 0.06, "is_integrated": False, "parking_area": 0},
            {"capacity": 40, "area": 0.1, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.3, "is_integrated": False, "parking_area": 0},
            {"capacity": 20, "area": 0.04, "is_integrated": True, "parking_area": 0.025},
            {"capacity": 40, "area": 0.08, "is_integrated": True, "parking_area": 0.03},
            {"capacity": 100, "area": 0.2, "is_integrated": True, "parking_area": 0.04},
        ],
    },
    {
        "code": "4.6",
        "name": "restaurant",
        "demand": 71,
        "accessibility": 30,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 45, "area": 0.02, "is_integrated": False, "parking_area": 0},
            {"capacity": 65, "area": 0.027, "is_integrated": False, "parking_area": 0},
            {"capacity": 90, "area": 0.04, "is_integrated": False, "parking_area": 0},
            {"capacity": 185, "area": 0.08, "is_integrated": False, "parking_area": 0},
            {"capacity": 50, "area": 0.02, "is_integrated": True, "parking_area": 0.025},
            {"capacity": 70, "area": 0.027, "is_integrated": True, "parking_area": 0.034},
            {"capacity": 100, "area": 0.04, "is_integrated": True, "parking_area": 0.05},
            {"capacity": 200, "area": 0.08, "is_integrated": True, "parking_area": 0.1},
        ],
    },
    {
        "code": "4.6",
        "name": "bar_pub",
        "demand": 25,
        "accessibility": 15,
        "land_use": ["residential", "mixed_use", "business"],
        "bricks": [
            {"capacity": 30, "area": 0.06, "is_integrated": False, "parking_area": 0},
            {"capacity": 50, "area": 0.01, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.035, "is_integrated": False, "parking_area": 0},
            {"capacity": 30, "area": 0.04, "is_integrated": True, "parking_area": 0.015},
            {"capacity": 50, "area": 0.009, "is_integrated": True, "parking_area": 0.0025},
            {"capacity": 100, "area": 0.025, "is_integrated": True, "parking_area": 0.009},
        ],
    },
    {
        "code": "3.6.2",
        "name": "park",
        "demand": 150,
        "accessibility": 30,
        "land_use": [],
        "bricks": [
            {"capacity": 270, "area": 12, "is_integrated": False, "parking_area": 0},
            {"capacity": 2100, "area": 68, "is_integrated": False, "parking_area": 0},
            {"capacity": 5500, "area": 168, "is_integrated": False, "parking_area": 0},
            {"capacity": 5480, "area": 96, "is_integrated": False, "parking_area": 0},
            {"capacity": 17800, "area": 175, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "4.7",
        "name": "hotel",
        "demand": 9,
        "accessibility": 60,
        "land_use": ["mixed_use", "business", "recreation"],
        "bricks": [
            {"capacity": 300, "area": 2.4, "is_integrated": False, "parking_area": 0},
            {"capacity": 500, "area": 2.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 900, "area": 3.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 1500, "area": 4, "is_integrated": False, "parking_area": 0},
            {"capacity": 2200, "area": 7.7, "is_integrated": False, "parking_area": 0},
            {"capacity": 300, "area": 2.4, "is_integrated": True, "parking_area": 0.015},
            {"capacity": 500, "area": 2.7, "is_integrated": True, "parking_area": 0.017},
            {"capacity": 900, "area": 3.2, "is_integrated": True, "parking_area": 0.02},
            {"capacity": 1500, "area": 4, "is_integrated": True, "parking_area": 0.025},
        ],
    },
    {
        "code": "3.6.3",
        "name": "zoo",
        "demand": 2,
        "accessibility": 60,
        "land_use": ["business"],
        "bricks": [
            {"capacity": 2975, "area": 7.2, "is_integrated": False, "parking_area": 0},
            {"capacity": 100, "area": 0.35, "is_integrated": False, "parking_area": 0},
        ],
    },
    {
        "code": "3.2.3",
        "name": "post",
        "demand": 933,
        "accessibility": 10,
        "land_use": ["residential", "mixed_use", "business", "recreation", "special"],
        "bricks": [
            {"capacity": 400, "area": 0.005, "is_integrated": True, "parking_area": 0.005},
            {"capacity": 480, "area": 0.006, "is_integrated": True, "parking_area": 0.06},
            {"capacity": 800, "area": 0.01, "is_integrated": True, "parking_area": 0.01},
        ],
    },
    {
        "code": "8.3",
        "name": "police",
        "demand": 5,
        "accessibility": 10,
        "land_use": [
            "residential",
            "mixed_use",
            "business",
            "recreation",
            "special",
            "industrial",
            "agriculture",
            "transport",
        ],
        "bricks": [
            {"capacity": 60, "area": 0.07, "is_integrated": False, "parking_area": 0},
            {"capacity": 90, "area": 0.11, "is_integrated": False, "parking_area": 0},
            {"capacity": 450, "area": 0.55, "is_integrated": False, "parking_area": 0},
        ],
    },
]
